import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * http://tools.android.com */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

    /**
     * https://developer.android.com/studio */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/IIIuminator/JMusicBotAndroid */
    const val jmusicbotandroid: String = "com.github.IIIuminator:JMusicBotAndroid:" +
            Versions.jmusicbotandroid

    const val timbersentry: String = "com.github.IIIuminator:timberSentry:" + Versions.timbersentry

    const val com_github_triplet_play_gradle_plugin: String =
            "com.github.triplet.play:com.github.triplet.play.gradle.plugin:" +
            Versions.com_github_triplet_play_gradle_plugin

    /**
     * http://developer.android.com/tools/extras/support-library.html */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * https://github.com/mikepenz/Android-Iconics */
    const val community_material_typeface: String = "com.mikepenz:community-material-typeface:" +
            Versions.community_material_typeface

    /**
     * https://github.com/mikepenz/FastAdapter */
    const val fastadapter_commons: String = "com.mikepenz:fastadapter-commons:" +
            Versions.fastadapter_commons

    /**
     * https://github.com/mikepenz/FastAdapter */
    const val fastadapter_extensions: String = "com.mikepenz:fastadapter-extensions:" +
            Versions.fastadapter_extensions

    /**
     * https://github.com/mikepenz/FastAdapter */
    const val fastadapter: String = "com.mikepenz:fastadapter:" + Versions.fastadapter

    /**
     * https://github.com/mikepenz/Android-Iconics */
    const val iconics_core: String = "com.mikepenz:iconics-core:" + Versions.iconics_core

    /**
     * https://github.com/square/moshi */
    const val moshi: String = "com.squareup.moshi:moshi:" + Versions.moshi

    /**
     * https://github.com/square/picasso/ */
    const val picasso: String = "com.squareup.picasso:picasso:" + Versions.picasso

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/getsentry/sentry-java */
    const val sentry_android_gradle_plugin: String = "io.sentry:sentry-android-gradle-plugin:" +
            Versions.sentry_android_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://github.com/Kotlin/kotlinx.coroutines */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" +
            Versions.kotlinx_coroutines_android

    /**
     * https://github.com/zTrap/Android-Iconics-Kt */
    const val core_kt: String = "ru.ztrap.iconics:core-kt:" + Versions.core_kt
}
