import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [appcompat website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * [constraintlayout website](http://tools.android.com) */
    const val constraintlayout: String =
            "androidx.constraintlayout:constraintlayout:" + Versions.constraintlayout

    /**
     * [core-ktx website](http://developer.android.com/tools/extras/support-library.html) */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * [fragment-ktx website](http://developer.android.com/tools/extras/support-library.html) */
    const val fragment_ktx: String = "androidx.fragment:fragment-ktx:" + Versions.fragment_ktx

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
            "com.android.tools.build:gradle:" + Versions.com_android_tools_build_gradle

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * [JMusicBotAndroid website](https://github.com/IIIuminator/JMusicBotAndroid) */
    const val jmusicbotandroid: String =
            "com.github.IIIuminator:JMusicBotAndroid:" + Versions.jmusicbotandroid

    const val timbersentry: String = "com.github.IIIuminator:timberSentry:" + Versions.timbersentry

    const val com_github_triplet_play_gradle_plugin: String =
            "com.github.triplet.play:com.github.triplet.play.gradle.plugin:" + Versions.com_github_triplet_play_gradle_plugin

    /**
     * [material website](http://developer.android.com/tools/extras/support-library.html) */
    const val material: String = "com.google.android.material:material:" + Versions.material

    /**
     * [community-material-typeface website](https://github.com/mikepenz/Android-Iconics) */
    const val community_material_typeface: String =
            "com.mikepenz:community-material-typeface:" + Versions.community_material_typeface

    /**
     * [fastadapter-commons website](https://github.com/mikepenz/FastAdapter) */
    const val fastadapter_commons: String =
            "com.mikepenz:fastadapter-commons:" + Versions.fastadapter_commons

    /**
     * [fastadapter-extensions website](https://github.com/mikepenz/FastAdapter) */
    const val fastadapter_extensions: String =
            "com.mikepenz:fastadapter-extensions:" + Versions.fastadapter_extensions

    /**
     * [fastadapter website](https://github.com/mikepenz/FastAdapter) */
    const val fastadapter: String = "com.mikepenz:fastadapter:" + Versions.fastadapter

    /**
     * [iconics-core website](https://github.com/mikepenz/Android-Iconics) */
    const val iconics_core: String = "com.mikepenz:iconics-core:" + Versions.iconics_core

    /**
     * [moshi website](https://github.com/square/moshi) */
    const val moshi: String = "com.squareup.moshi:moshi:" + Versions.moshi

    /**
     * [picasso website](https://github.com/square/picasso/) */
    const val picasso: String = "com.squareup.picasso:picasso:" + Versions.picasso

    /**
     * [sentry-android-gradle-plugin website](https://github.com/getsentry/sentry-java) */
    const val sentry_android_gradle_plugin: String =
            "io.sentry:sentry-android-gradle-plugin:" + Versions.sentry_android_gradle_plugin

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [kotlin-android-extensions website](https://kotlinlang.org/) */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-annotation-processing-gradle website](https://kotlinlang.org/) */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.kotlinx_coroutines_android

    /**
     * [core-kt website](https://github.com/zTrap/Android-Iconics-Kt) */
    const val core_kt: String = "ru.ztrap.iconics:core-kt:" + Versions.core_kt
}
