import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val appcompat: String = "1.1.0"

  const val constraintlayout: String = "2.0.0-beta2"

  const val core_ktx: String = "1.1.0"

  const val androidx_lifecycle: String = "2.2.0-alpha05"

  const val androidx_navigation: String = "2.2.0-alpha03"

  const val preference_ktx: String = "1.1.0"

  const val recyclerview: String = "1.1.0-beta04"

  const val aapt2: String = "3.5.0-5435860"

  const val com_android_tools_build_gradle: String = "3.5.0"

  const val lint_gradle: String = "26.5.0"

  const val crashlytics: String = "2.10.1"

  const val com_diffplug_gradle_spotless_gradle_plugin: String = "3.24.2"

  const val com_github_triplet_play_gradle_plugin: String = "2.4.1"

  const val material: String = "1.1.0-alpha10"

  const val google_services: String = "4.3.2"

  const val jmusicbot_client: String = "0.8.5"

  const val timber: String = "4.7.1"

  const val splitties_fun_pack_android_material_components: String = "3.0.0-alpha06"

  const val community_material_typeface: String = "3.5.95.1-kotlin" // available: "3.5.95.1"

  const val fastadapter_extensions_diff: String = "4.0.1"

  const val fastadapter_extensions_drag: String = "4.0.1"

  const val fastadapter_extensions_swipe: String = "4.0.1"

  const val fastadapter_extensions_ui: String = "4.0.1"

  const val fastadapter_extensions_utils: String = "4.0.1"

  const val fastadapter: String = "4.0.1"

  const val iconics_core: String = "4.0.0"

  const val moshi: String = "1.8.0"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.5.0" // available: "0.6.1"

  const val io_fabric_tools_gradle: String = "1.31.1"

  const val org_jetbrains_kotlin: String = "1.3.50"

  const val kotlinx_coroutines_android: String = "1.3.1"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "5.6.2"

  const val gradleCurrentVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
